services:
  - type: web
    name: calorie-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py import_food
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
